module.exports = {
    POINTS_PER_POST: 50,
    POINTS_COMMENT_TO_COMMENT_CREATOR: 10,
    POINTS_COMMENT_TO_POST_CREATOR: 1,
    POINTS_COMMENT_REACTION_TO_COMMENT_CREATOR: 1,
    POINTS_COMMENT_REACTION_TO_REACTION_CREATOR: 5,
};
